### ISSUE TITLE
Queue Bot is down

### ISSUE THREAD

**Issue by rustygentile** [ArrowM/Queue-Bot#1]
Any plans to bring it back up?

**Comment by ArrowM** [comment]
Yeah, it should be back up sometime today - been looking for a good hosting solution.

**Comment by rustygentile** [comment]
Cool. I find Heroku is pretty easy to use. There are probably cheaper options though.

**Comment by ArrowM** [comment]
It took longer than expected, but it should be live now. Hosting it on a raspberry pi
