### ISSUE TITLE
[Bug]Voice Pulling Bug

### ISSUE THREAD

**Issue by Arithium** [ArrowM/Queue-Bot#11]
The bot will continue to pull people from the queue even if you set the pull amount to 1 for a short period of time. We're needing the bot to just pull a single person, and then stop pulling from the voice channel until the admin is ready for the next person to get pulled.

**Comment by ArrowM** [comment]
Have you tried `!autofill {queue name} off`?

**Comment by Arithium** [comment]
> Have you tried `!autofill {queue name} off`?

Yes, it just says "Autofill must be ON or OFF". It didn't actually change the setting.

The command typed was "!autofill waiting_room off" which gave the argument parse error. I also believe this might be one of the issues we're facing, as we're being auto joined as soon as we re-enter the queue right away. 

 ` const returningMember = returningMembersCache.get(newVoiceChannel.id + "." + member.id);
      returningMembersCache.delete(newVoiceChannel.id + "." + member.id);`

      const withinGracePeriod = returningMember ? Date.now() - returningMember.time < +queueGuild.grace_period * 1000 : false;

      if (withinGracePeriod && returningMember.member) {
         await knex<QueueMember>("queue_members").insert(returningMember.member);
      } else {
         await QueueMemberTable.storeQueueMembers(newVoiceChannel.id, [member.id]);
      }
      SchedulingUtils.scheduleDisplayUpdate(queueGuild, newVoiceChannel);`

**Comment by ArrowM** [comment]
I am not able to reproduce this issue. Can you add me on Discord so I can ask a few questions? Arrow#5206

**Comment by AzureX1212** [comment]
I've sent you a request, Arthium and I are working together on setting up the bot for our server.
