### ISSUE TITLE
[Bug]Display of Users sometimes bugs out and displays discord ID instead

### ISSUE THREAD

**Issue by dariorthan** [ArrowM/Queue-Bot#16]
somtimes the queue bugs out for somebody and one of the users on the queue displays as their discord ID instead of their name. 
when that happens its usually only for that person, everyone else being fine.

**Comment by ArrowM** [comment]
This is an issue with the discord client, not the bot. <@264479399779237889> and <@!264479399779237889> are the plaintext formats used to mention users.
