### ISSUE TITLE
Server members seeing "ERROR: Missing permissions to use that command" when trying to /join queue

### ISSUE THREAD

**Issue by jkatofsky** [ArrowM/Queue-Bot#17]
We have a queue in a text channel, and often members of our server will see this sort of output when trying to use `/join`:

![image](https://user-images.githubusercontent.com/13226824/134563266-b933db24-70fa-40fd-aeda-48942243e81e.png)

I have tried to uninstall and reinstall the bot, as well as disabling "In Queue: ..." role feature to see if that was causing the issue, but it persists. I am a server admin and am unable to replicate this bug, but it has been reported many times by general members.

Any idea what could be causing this?

**Comment by ArrowM** [comment]
Pull latest and let me know if it's still broken.

**Comment by jkatofsky** [comment]
Silly question @ArrowM: how does one pull changes for the bot? Do I need to kick and reinstall it?

**Comment by ArrowM** [comment]
Oh, I thought you were hosting your own version. If you're using the one I host (it sounds like you are), then the change should already be live.
