### ISSUE TITLE
[Suggestion] Allow manual rearrangement of the queue

### ISSUE THREAD

**Issue by jdcoolha** [ArrowM/Queue-Bot#18]
Greetings,

How hard would it be to add a command for aa mod to manually rearrange the queue? E.G. something like '/move Username 2' would move them to position 2 in the queue.

**Comment by ArrowM** [comment]
Just added it, but I didn't test it very thoroughly. Can you give it try and let me know how it goes?

**Comment by jdcoolha** [comment]
Not quite working properly. As you can see some moves are not going to the right position.

In this case Nail was originally in pos 1, Terra was originally in pos 3.
![image](https://user-images.githubusercontent.com/1365088/149634218-7e8449a8-383b-4dd0-8161-7d7b89616c72.png)
![image](https://user-images.githubusercontent.com/1365088/149634234-f6c47e70-2305-417e-b4d6-6ab06aecf66d.png)

**Comment by ArrowM** [comment]
Could you please try again now and let me know.

**Comment by jdcoolha** [comment]
Appears to be functioning as expected, thanks much!
