### ISSUE TITLE
Last user is always kicked

### ISSUE THREAD

**Issue by Kiolali** [ArrowM/Queue-Bot#2]
We just tested the Queue-Bot with 2 users and with 3 users in a voice channel.
Behaviour with 2 users: user1 joined first, user2 joined second. After the queue bot was dragged to another voice chat, user1 was automatically dragged, which is correct. But then the queue is always empty although user2 should still be in the queue.

Behaviour with 3 users: user1 joined first, user2 joined second, user3 joined third. After the queue bot was dragged to another voice chat, user1 was automatically dragged, which is correct. But then the queue only contains user2. This behaviour is reproducible. The last user is always kicked.
Any Idea? Maybe it has something to do with the 4 seconds timer, because dragging 3 times the bot very fast works. All users in the queue are dragged.

Thanks in advance, 
Kiola

**Comment by ArrowM** [comment]
Thank you for the bug submission. I am able to recreate it and I'm looking into it now.
You can change the timer length using `!g {timer length}`. I'm seeing the issue even when the timer is set to 0.

**Comment by Kiolali** [comment]
Thank you. Same for me with the timer

**Comment by ArrowM** [comment]
Alright, should be fixed now.

**Comment by Kiolali** [comment]
Thanks!
