### ISSUE TITLE
Last person removed from queue after kicking another

### ISSUE THREAD

**Issue by jdcoolha** [ArrowM/Queue-Bot#3]
I've been noticing a pattern in voice channel queues where whenever I kick somebody from the queue, the last person in the Queue after the kick also gets removed, I presume after the grace period. This may be happening after I kick somebody who had already left but is still technically queued due to the grace period.

EDIT: The "last person" part of this may be misleading, come to think of it. It may remove whoever was moved to that queue position as a result of the kick

If needed, I have screen recordings of this happening a couple of times.

**Comment by ArrowM** [comment]
Good catch, I'm rewriting most of the code to use a new database library. I'll include a fix with that code. I should hopefully have it done in the next day or two.

**Comment by ArrowM** [comment]
Alright, the issue should be fixed now. Please let me know if you see it again. Thanks.
