### ISSUE TITLE
Potential update for the readme?

### ISSUE THREAD

**Issue by VanessaHenderson** [ArrowM/Queue-Bot#4]
We use the queue bot (which is great and THANK YOU!) in a few discord servers and the dragging to another channel stopped working.
We narrowed it down to when you drag Queuebot from one voice channel with a queue, to another voice channel which also has a queue, queuebot doesn't move anyone and starts working for the new queue instead.

This took us awhile to figure out so it might be worth putting something to that effect into the readme?

Just to clarify: 
Our use case for queuebot is queueing up people to come into the live gaming chat for twitch streams. We have a queue in The Waiting Room and a queue in the Live Gaming chat voice channels. This way we can see that we are rotating people correctly based on the order that they joined the Live Gaming chat.

So no actually a bug but a potential enhancement to the readme :)

Also adding things like what the default values are for certain commands (such as autofill, pullnum, cleanup etc) might also be useful :)

**Comment by ArrowM** [comment]
Thanks for the feedback. I'll update the readme. Not moving users when the bot is moved between queues was intentional, but something I could change. I have no idea what most people would prefer for that behavior, do you think most people would want it to move users? I could probably make it behave that way.

**Comment by VanessaHenderson** [comment]
I don't know what most people would prefer because I don't know anyone elses usecases!
Maybe it is something that could be configurable? Like lock the queuebot user to work for a specific queue if you want to?

But if not its not the end of the world :)
