### ISSUE TITLE
[Problems] a couple of problems i noticed after building the bot

### ISSUE THREAD

**Issue by ScaredyCatX** [ArrowM/Queue-Bot#7]
after building the bot there is somethings that doesn't work properly 

1- kick command doesn't get recognized and doesn't work (after turning cleanup on the commands doesn't get deleted )
2- when adding someone to the blacklist they get kicked from the queue but they can join again in the same queue
3- join commands only remove the person in queue but doesn't add them to it 
4- mention queue doesn't work 

these all work when i use the bot from top.gg but when rebuilding the code it doesn't 
i though i messed something up so i built the code without changing anything and still the same problem persist

**Comment by ArrowM** [comment]
Thank you for opening this issue.
1, 4 - I'm not seeing these issues on my own instance of the bot. Feel free to add me on discord (Arrow#5206) and we can dm to troubleshoot.
2, 3 - Good catches. These were legitimate bugs and I just pushed a couple fixes.
